pipeline{
    agent any
    environment {
        PATH ="$PATH c:\Program Files\apache-maven-3.9.0"
  }
    stages{
       stage('GetCode'){
            steps{
                git c:\Program Files\git
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'sonarscanner4.0';
        steps{
        withSonarQubeEnv('sonarqube-8.9') { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}
